repos:
  - repo: local
    hooks:
      - id: eslint-fix
        name: ESLint fix
        language: system
        entry: pnpm eslint --fix
        files: '\.(js|jsx|ts|tsx|cjs|mjs|cts|mts)$'
        pass_filenames: true

      - id: stylelint-fix
        name: Stylelint fix (CSS/SCSS/LESS/Vue/HTML)
        language: system
        entry: pnpm stylelint --fix
        files: '\.(css|scss|less|vue|html)$'
        pass_filenames: true
